create table song (
SONGNO number PRIMARY KEY,
TITLE varchar2(100) not null,
YADDRESS VARCHAR2(20) not null,
SINGER VARCHAR2(30) NOT NULL
);

CREATE TABLE SONGREPLY(
SONGNO NUMBER,
CONSTRAINT FK_SONGNO FOREIGN KEY(SONGNO) REFERENCES SONG (SONGNO),
COMMENTID NUMBER,
USERID VARCHAR2(20),
REP_CONTENT VARCHAR(90),
REP_DATE DATE
);

select * from song;