create table song (
SONGNO number PRIMARY KEY,
TITLE varchar2(100) not null,
YADDRESS VARCHAR2(20) not null,
SINGER VARCHAR2(30) NOT NULL
);

DROP TABLE SONGREPLY;

CREATE TABLE SONGREPLY(
COMMENTNO NUMBER PRIMARY KEY,
SONGNO NUMBER NOT NULL,
CONSTRAINT FK_SONGNO FOREIGN KEY (SONGNO) REFERENCES SONG (SONGNO),
COMMENTID NUMBER NOT NULL,
USERID VARCHAR2(20) NOT NULL,
REP_CONTENT VARCHAR(90) NOT NULL,
REP_DATE DATE
);

insert into song (SONGNO, TITLE, YADDRESS, SINGER) values(12345, '레베카', 'JUEoW9_BAS8', '옥주현');
commit;
